// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package hello

import (
	"kmitl-mvc/api/hello"
)

type ControllerV1 struct{}

func HelloV1() hello.IHelloV1 {
	return &ControllerV1{}
}
